# 서버 포트 변경
server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/soj
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true